version: '3.8'

services:
  # The trainer service: only runs if you explicitly call it.
  # Command to run it: docker-compose run --rm trainer
  trainer:
    image: model:latest
    build:
      context: .
      dockerfile: Docker/model_training.dockerfile
    env_file:
      - .env
    volumes:
      - ./engine_artifacts:/app/engine_artifacts
    profiles:
      - train # This stops it from running automatically

  # The backend service: serves the FastAPI backend and static frontend
  api:
    image: philo-backend:latest
    build:
      context: .
      dockerfile: Docker/backend.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./engine_artifacts:/app/engine_artifacts
